repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.7
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  # - repo: https://github.com/pdm-project/pdm
  #   rev: 2.14.0 # a PDM release exposing the hook
  #   hooks:
  #     - id: pdm-export
  #       # command arguments, e.g.:
  #       args: ['-o', 'requirements.txt', '--without-hashes']
  #       files: ^pdm.lock$